timeout: 3600s
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'pull-app'
    args:
      - 'pull'
      - '${_DOCKER_USERNAME}/go-grpc-sample:latest'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-login'
    args:
      - 'login'
      - '-u' 
      - '${_DOCKER_USERNAME}'
      - '-p' 
      - '${_DOCKER_PASSWORD}'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-app'
    args:
      - 'build'
      - '-t'
      - '${_DOCKER_USERNAME}/go-grpc-sample:${REVISION_ID}'
      - '-t'
      - '${_DOCKER_USERNAME}/go-grpc-sample:latest' 
      - '.'
    waitFor: ['pull-app']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-app-image-revision-id'
    args:
      - 'push' 
      - '${_DOCKER_USERNAME}/go-grpc-sample:${REVISION_ID}'
    waitFor: ['build-app', 'docker-login']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-app-image-latest'
    args:
      - 'push' 
      - '${_DOCKER_USERNAME}/go-grpc-sample:latest'
    waitFor: ['build-app', 'docker-login']

  # -------------- deploy ----------------
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'decrypt-helm-secret'
    args:
      - 'kms'
      - 'decrypt'
      - '--location'
      - 'global'
      - '--keyring'
      - '${_KEYRING}'
      - '--key'
      - '${_KEY}'
      - '--ciphertext-file'
      - 'helm/go-grpc-sample/templates/_enc_secret.yaml'
      - '--plaintext-file'
      - 'helm/go-grpc-sample/templates/secret.yaml'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'decrypt-helm-values'
    args:
      - 'kms'
      - 'decrypt'
      - '--location'
      - 'global'
      - '--keyring'
      - '${_KEYRING}'
      - '--key'
      - '${_KEY}'
      - '--ciphertext-file'
      - 'helm/go-grpc-sample/values.yaml.enc'
      - '--plaintext-file'
      - 'helm/go-grpc-sample/_enc_values.yaml'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-credentials'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '${_CLUSTER_NAME}'
      - '--zone=${_ZONE}'
      - '--project=${PROJECT_ID}'
    waitFor: ['-']

  - name: 'docker.io/${_DOCKER_USERNAME}/helm'
    id: 'helm-lint'
    args:
      - 'lint'
      - 'helm/go-grpc-sample'
    waitFor: ['docker-login', 'push-app-image-revision-id', 'get-credentials', 'decrypt-helm-values', 'decrypt-helm-secret']

  - name: 'docker.io/${_DOCKER_USERNAME}/helm'
    id: 'helm-install'
    args:
      - 'install' 
      - '--name'
      - 'go-grpc-sample'
      - '--set' 
      - 'grpcImageTag=${REVISION_ID}'
      - 'helm/go-grpc-sample'