apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-server-config
data:
  SERVER_PORT: "{{ .Values.grpcPort }}"

--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data: 
  POSTGRES_USER: go-app
  POSTGRES_DB: some-table
  POSTGRES_SSLMODE: disable
  POSTGRES_HOST: {{ .Values.postgresHost }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  book.sql: |
    create table books
    (
        id serial primary key,
        title text,
        author text,
        description text,
        pages integer,
        price integer
    );