apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: db 
spec:
  containers:
  - name: postgres-container
    image: postgres:9.6
    ports:
      - containerPort: 5432
    envFrom:
      - configMapRef:
          name: postgres-config
      - secretRef:
          name: postgres-credential
    volumeMounts:
      - name: sql
        mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: sql
      configMap:
        name: postgres-init
        items:
          - key: book.sql
            path: book.sql
